### ISSUE TITLE
v1.0.0 Download to SciDrive fails with error

### ISSUE THREAD

**Issue by thakar** [idies/CasJobs#12] opened 2015-06-22 21:34 UTC
When I try to download a MyDB table to SciDrive, the download fails with the following error on the CJ output page:
The remote server returned an error: (500) Internal Server Error. at System.Net.HttpWebRequest.GetResponse() at edu.jhu.Cas.Service.OutputThread.ProcessJob(Job job) in e:\Projects\github\idies\CasJobs\JobsService\OutputThread.cs:line 133

This is probably because the test user has not previously logged into SciDrive and created a first_container. If that is required, then it should be specified in the test script.  A better solution would be to create first_container when a user first attempts to check in a file, since it is the default contianer anyway.

**Comment by raddick** [comment] 2015-06-23 15:16
I just tried test CJ_SCIDRV_1 (as of 6/23/2015 at 11 AM), and it worked fine for me. Has this issue been fixed?

**Comment by thakar** [comment] 2015-06-23 15:38
Yeah it's working now.  As I mentioned in the report, it was an issue with
the test script, in that it did not say that you had to log in to SciDrive
first so a default container is created.  Or maybe that was a bug in
SciDrive that's been fixed now (default container not being created unless
user logs in first time?).

      Ani


--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
Do not commit the error, common among the young, of assuming that
if you cannot save the whole of mankind, you have failed.
[Jan de Hartog]

**Comment by mtaghiza** [comment] 2015-06-25 18:46
can't reproduce error anymore (provided the login-portal has been restarted recently). Maybe solved by Mitya. Closing it.

**Closed by mtaghiza** 2015-06-25 18:46 UTC
Labels: bug
