### ISSUE TITLE
v1_0_0: (minor) Folder name input field not displayed when you navigate back to MyDB download page after doing a SciDrive download

### ISSUE THREAD

**Issue by thakar** [idies/CasJobs#39] opened 2015-07-01 18:58 UTC
After downloading a MyDB table to SciDrive, I used the browser back button to go back to the MyDB page from the Output page. The table that I just downloaded was displayed, and the download option selected was still showing as "SciDrive", but the input field to specify the SciDrive folder name was missing to the right of it. You may have to click "Download" again in the table menu for this to happen.

**Comment by dmedv** [comment] 2015-07-20 21:06
Looks like the problem is specific to Chrome. It works fine in Firefox. I have added an additional refresh call, now it should work in both browsers. Marking as closed.

**Closed by dmedv** 2015-07-20 21:06 UTC
Labels: bug, sciserver_v1_0_0
