### ISSUE TITLE
v1_0_0: MyDB download to SciDrive giving timeout error

### ISSUE THREAD

**Issue by thakar** [idies/CasJobs#37] opened 2015-07-01 18:51 UTC
When I try to download a MyDB table from CasJobs to SciDrive, I'm repeatedly getting a timeout error even though the table is pretty small:
The operation has timed out at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context) at System.Net.HttpWebRequest.GetRequestStream() at edu.jhu.Cas.Service.OutputThread.CreateSciDriveContainer(String path, String token) in e:\Projects\github\idies\CasJobs\JobsService\OutputThread.cs:line 284 at edu.jhu.Cas.Service.OutputThread.ProcessJob(Job job) in e:\Projects\github\idies\CasJobs\JobsService\OutputThread.cs:line 122

**Comment by dmedv** [comment] 2015-07-17 22:42
Tried with several tables of small to medium size. Could not reproduce the error. It was probably due to some temporary problem with SciDrive which has been resolved. I'm marking this as closed for now...

**Comment by dmedv** [comment] 2015-07-20 18:13
Looks like HTTP connections did not get closed properly, which led to occasional timeout errors. I have changed the way SciDrive REST services are called by JobsService. Should be fixed now, but probably needs more testing. Marking as closed.

**Closed by dmedv** 2015-07-20 18:13 UTC
Labels: bug, sciserver_v1_0_0
